#!/usr/bin/env python3
"""
YouTube Cookie Exporter for Firefox
Extracts YouTube cookies from Firefox profile and saves in Netscape format for yt-dlp

Requirements:
    pip install browser-cookie3

Usage:
    python export_firefox_cookies.py
    
The script will automatically find your Firefox profile and export YouTube cookies
to cookies.txt in the current directory.
"""

import os
import sys
import sqlite3
import json
from pathlib import Path
from datetime import datetime, timezone

def find_firefox_profile():
    """Find the Firefox profile directory."""
    # Firefox profile locations for different OS
    if sys.platform == "linux":
        base_path = Path.home() / ".mozilla" / "firefox"
    elif sys.platform == "darwin":  # macOS
        base_path = Path.home() / "Library" / "Application Support" / "Firefox" / "Profiles"
    elif sys.platform == "win32":  # Windows
        base_path = Path(os.getenv('APPDATA')) / "Mozilla" / "Firefox" / "Profiles"
    else:
        raise OSError(f"Unsupported OS: {sys.platform}")
    
    if not base_path.exists():
        raise FileNotFoundError(f"Firefox profile directory not found at {base_path}")
    
    # Find the default profile (usually ends with .default-release)
    profiles = list(base_path.glob("*.default-release"))
    if not profiles:
        # Try any profile
        profiles = [p for p in base_path.iterdir() if p.is_dir() and not p.name.startswith('.')]
    
    if not profiles:
        raise FileNotFoundError("No Firefox profiles found")
    
    # Use the most recently modified profile
    profile = max(profiles, key=lambda p: p.stat().st_mtime)
    print(f"Using Firefox profile: {profile.name}")
    return profile

def export_firefox_cookies(output_file="cookies.txt"):
    """Export YouTube cookies from Firefox to Netscape format."""
    
    try:
        profile_path = find_firefox_profile()
    except (FileNotFoundError, OSError) as e:
        print(f"Error: {e}")
        print("\nMake sure Firefox is installed and you have visited YouTube at least once.")
        return False
    
    cookies_db = profile_path / "cookies.sqlite"
    if not cookies_db.exists():
        print(f"Error: Firefox cookies database not found at {cookies_db}")
        return False
    
    # Make a temporary copy of the database (Firefox locks it)
    temp_db = "temp_cookies.sqlite"
    try:
        import shutil
        shutil.copy2(cookies_db, temp_db)
    except Exception as e:
        print(f"Error copying cookies database: {e}")
        print("\nTip: Close Firefox completely and try again.")
        return False
    
    try:
        # Connect to the temporary database
        conn = sqlite3.connect(temp_db)
        cursor = conn.cursor()
        
        # Query YouTube cookies
        cursor.execute("""
            SELECT host, name, value, path, expiry, isSecure
            FROM moz_cookies
            WHERE host LIKE '%youtube.com%' OR host LIKE '%google.com%'
            ORDER BY host, name
        """)
        
        cookies = cursor.fetchall()
        conn.close()
        
        if not cookies:
            print("Warning: No YouTube cookies found.")
            print("Please sign in to YouTube in Firefox first, then run this script again.")
            return False
        
        # Write cookies in Netscape format
        with open(output_file, 'w') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file was generated by export_firefox_cookies.py\n")
            f.write("# Edit at your own risk.\n\n")
            
            for cookie in cookies:
                host, name, value, path, expiry, is_secure = cookie
                
                # Format: domain, flag, path, secure, expiration, name, value
                # flag is TRUE if domain starts with dot
                domain_flag = "TRUE" if host.startswith('.') else "FALSE"
                secure_flag = "TRUE" if is_secure else "FALSE"
                
                # Handle expiry (Firefox stores as Unix timestamp)
                expiry_str = str(expiry) if expiry else "0"
                
                line = f"{host}\t{domain_flag}\t{path}\t{secure_flag}\t{expiry_str}\t{name}\t{value}\n"
                f.write(line)
        
        print(f"\n✓ Successfully exported {len(cookies)} cookies to {output_file}")
        print(f"\nNext steps:")
        print(f"1. Copy this file to your server:")
        print(f"   scp {output_file} root@your-server:~/web/youtube_downloader/cookies/")
        print(f"2. Restart the Docker container:")
        print(f"   docker compose restart")
        
        return True
        
    except sqlite3.Error as e:
        print(f"Database error: {e}")
        return False
    
    finally:
        # Clean up temporary database
        if os.path.exists(temp_db):
            try:
                os.remove(temp_db)
            except:
                pass

def main():
    """Main function."""
    print("=" * 60)
    print("YouTube Cookie Exporter for Firefox (Kali Linux)")
    print("=" * 60)
    print()
    
    # Check if Firefox is running
    try:
        import subprocess
        result = subprocess.run(['pgrep', '-f', 'firefox'], capture_output=True)
        if result.returncode == 0:
            print("⚠ WARNING: Firefox is currently running!")
            print("For best results, please close Firefox and run this script again.")
            response = input("\nContinue anyway? (y/n): ").strip().lower()
            if response != 'y':
                print("Aborted.")
                return
            print()
    except:
        pass
    
    # Export cookies
    success = export_firefox_cookies("cookies.txt")
    
    if success:
        print("\n" + "=" * 60)
        print("Export completed successfully!")
        print("=" * 60)
        sys.exit(0)
    else:
        print("\n" + "=" * 60)
        print("Export failed. Please check the errors above.")
        print("=" * 60)
        sys.exit(1)

if __name__ == "__main__":
    main()
