# Generated by Django 6.0 on 2025-12-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_downloader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodownload',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='format_type',
            field=models.CharField(choices=[('mp4', 'MP4 Video'), ('mp3', 'MP3 Audio')], default='mp4', max_length=10),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='videodownload',
            name='uploader',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='videodownload',
            name='quality',
            field=models.CharField(choices=[('best', 'Best Quality'), ('1080p', '1080p'), ('720p', '720p'), ('480p', '480p'), ('worst', 'Lowest Quality')], default='720p', max_length=10),
        ),
        migrations.AlterField(
            model_name='videodownload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('fetching', 'Fetching Info'), ('downloading', 'Downloading'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
