# Generated by Django 6.0 on 2025-12-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_downloader', '0002_videodownload_duration_videodownload_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodownload',
            name='session_id',
            field=models.CharField(db_index=True, default='legacy', max_length=64),
        ),
    ]
